---
title: "Technical Write Up"
author: "Harrison Liao, Freezer Yang, Kaushal Boommena"
date: "11/20/2019"
output: html_document
---

### Project Code name: To be or not to be, the generation that reaches the end

## Project Title:  Suicide Comparison of Generations

### Team members (names and contacts
- Harrison Liao 
  - hxliaoay@uw.edu  
- Kaushal Bommena 
  - bommek@uw.edu  
-Freezer Yang  
  -wfeng98@uw.edu  

> Affiliation  
>  Info-201: Technical Foundations of Informatics: The Information School, University of Washington, Autumn 2019

### 1.0 Introduction  
#### 1.1 Problem Situation?  
Suicide has been an issue for mankind forever, and there has been causes of all sorts.  According to the World Health Organization, every year close to 800,000 people took their lives by their own hands, and many more attempt but failed (Suicide).  What’s even more concerning is that it’s the third leading cause of teenagers (15-19-year-olds), those that make up the next generation of the society (Suicide).  Another thing the article mentions is that almost 80% of the suicide cases occur in middle and low income countries, which brings the factor of financial situation into the equation.  With almost 800,000 lives lost each year and increasing, we need to understand that this is an issue that affects every single living person may it be themselves or their family and friends that put an end to themselves -- not just those of the specific groups mentioned above, as they are just more discriminated against for this issue.  (Note: the term discrimination here follows the definition in Stanford Encyclopedia of Philosophy (Altman).)  The severity of this issue is something that not only all individuals need to act on for themselves and others, but high up the government needs to resolve as well, considering this is something that is increasingly affecting every member of the society, and institutionalized help would allow those who are isolated or in dire need to get help more easily.  Nowadays most countries have suicide hotlines and other facilities, yet they don’t necessarily reach to those in need.  In this case we look into other factors that might influence suicide in this project, in hope that we can fix other factors to lessen the tension of the issue.  
#### 1.2 What is the problem?  
In simple words, people are dying.  In a more complex matter, people are dying because they choose to do so themselves, and they do it because other life matters are so difficult to them that even death seems like the easier option.  These issues that cause people to choose death may be financial matters, emotional problems, relationship issues, or something else -- this matter will be further discussed in the project later on.

#### 1.3 Why does it matter?  
As stated before, this is a growing issue that affects all human beings and must be resolved.  If issues like such that puts matter into life and death can’t be resolved, it becomes a major obstacle for humanity to advance any further and such progression would affect the living quality of every single human being that walks the earth.  Even if one does not care about such objective, they should still value the lives of their loved ones more or less.

#### 1.4 How will it be addressed?  
The unit of analysis here would be generation groups of either sex of a country of a certain year.  (Note: cases of intersex or more complex matters are not included here as they are an extreme minority.  We understand that these are extremely vulnerable groups and there are specific LGBTQ+ organizations that provides extra support for these individuals.)  For complete list of variables of each data entry please refer to Appendix 1: Data Dictionary.  For specific variables we’re looking at countries, the gdp per capita of the country, the generation (age group), the year and sex of the unit of analysis.  For visualizations we aim to use a scatter plot of year to suicide rates with each point being a country as the framework.  From here we can break down the scatter plot into multiples by brackets of sex, gdp per capita, or generations.  To put the factor of fiscal matters we can substitute the year variable and look at the relationship of gdp per capita to suicide rates, and we can break it down into multiple plots by brackets of sex, years, or generations.  The final product would be simpler than proposed as we hope to present this to the general population and to bring awareness to everyone.  

### 2.0 Research Questions  
1. Does gdp per capita affect the suicide rates?
2. How suicide rates have been changed throughout each generation?
3. How does sex affect suicide rates?
### 3.0 Possible Data Sets  
[Suicide Rates Overview 1985 to 2016](https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016)
  - This is data set was uploaded to kaggle by the user Rusty, sourcing from data of World Bank, United Nations Development Program, and World Health Organization.  This data set was pieced together with the article “Suicide in the Twenty-First Century” of user Szamil that did a similar analysis with the data on World Health Organization’s dataset of suicide (Rusty).  The data set that has been put together here is nothing but “suicide prevention” in the eyes of Rusty, and in order to contribute to this common goal, we need to analyze the data to find trends that could help us understand the situation more to solve the issue.  In the data set each observation is a group of people of a certain generation (age group), either sex, of country, and its suicide rate of a year.  The variables of the observations in the data include: country, year, sex, age (grouped), number of suicides of the group, population of the group, suicide percentage of the group, country-year (simply for easier sorting), Human Development Index, gdp for year, gdp per capita for year, and generation.  This data does not include those measures of people of intersex which could be that it isn’t properly tracked and is an extreme minor part of population.  There does appear to be some missing variables of older data as it couldn’t be tracked properly.  For the dataset we extract from one that will be eliminated the age section as it somewhat overlaps with the category of generation.  It’s not exactly synonymous, but we believe that the background people grow up with matters a lot more than numbers that might be a bit more accurate -- this would be easier for the general audience as well.  Another thing is we choose to keep only gdp per capita instead of gdp of the whole country, as the gdp of the whole country does not represent the living situation of the people as the size of countries vary a lot.  The raw numbers of suicide and population has been removed as the variable of suicide per 100,000 ppl is the suicide rate of the group, and shows how severe the problem is.  Population might indicate the size of a country and its relation to suicide, but that is out of the discussion here.  The Human Development Index is missing a lot of data, and will consider to be dropped as well.
 
### 4.0 Information Visualizations  
To answer the Research questions, we will use a scatter plot of gdp per capita vs suicide rates, with each dot being an observation.  The analysis of this would answer research question 1.  To answer research question 2 we would give the option to change the colors of the observations by generation; and for question 3 we could apply the same concept and change the color by sex.  If the observation is missing gdp per capita, it would be eliminated from the scatterplot of gdp per capita vs suicide rates.  On the sidebar there would be options to show only certain sex, certain generations, etc.  
 
### 5.0 Technical description of Shiny application  
- File loaded format: all csv  
- Major libraries: shiny, plotly, dplyr, shinydashboard, rsconnect, and ggplot2
- File organization: under the main application there's the server and UI file, and page elements are under the UI file

### 6.0 Conclusion
> to be determined, as we don't have enough understanding to comfortably draw conclusions    

#### References  
- Altman, Andrew, "Discrimination", The Stanford Encyclopedia of Philosophy (Winter 2016 Edition), Edward N. Zalta (ed.)
  - https://plato.stanford.edu/archives/win2016/entries/discrimination/    
- Rusty. Suicide Rates Overview 1985 to 2016. Kaggle, 1 Dec. 2018  
  - https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016
- “Suicide.” World Health Organization, World Health Organization, 2 Sept. 2019  
  - https://www.who.int/news-room/fact-sheets/detail/suicide.
- [Szamil]. (2017). Suicide in the Twenty-First Century.  
  - https://www.kaggle.com/szamil/suicide-in-the-twenty-first-century/notebook
 
#### Appendix 1: Data Dictionary
```{r, echo=FALSE}
suppressMessages(library(knitr))
p <- read.csv("dict.csv")
kable(p)
````
#### Appendix 2: Reflections
- Freezer: I learned how to visualize data using the shiny app. When I first tried to set up the connection with ui.file and server.file, I was really frustrated, plus I wasn't very familiar with the shiny app. No matter how many times I read the textbook or even watched the lecture video, I didn't know how to get this project to start. It took me almost half a day to solve the problem of loading the plot. At the behest of a friend, I finally understood the shiny app fundamental. I hope that in the rest of the project, our team members can help each other out, determined not to procrastinate, in the premise of quality assurance, able to complete and successfully deliver this project. Data visualization to me has endless knowledge. No matter how you display data, there's no right or wrong answer to this, though the audience must know what story you are telling.

- Harrison: For me this is one of the first large coding project I've done.  This project felt a lot harder to get by than it should, perhaps due to lacking a group member and everyone has to put in extra work.  Nevertheless, the amount of experience in coding with R is there regardless.  Having experience in SOC225 which is a similar curriculum with assignments through the quarter + a personal project of the same but on a simpler scale, this class surely lived up to its name of helping me learn the technical foundations of R.  On a second thought I do find it unfortunate that the class simply went through a project for the sake of doing a project when there's so much more to discuss -- when another class can spend about 50% of it on Cathy O'Neil's book yet we only have it as a supplementary textbook and not used for the majority of the class.   

- Kaushal: Through this project, I am gradually understanding how to approach the concept of data science, in that the beauty of it is within its vagueness. Given a few sets of data, we are able to ask ourselves  meaningful research questions and detect trends out of numbers and lines. There were many parts of the project I found to be quite difficult at times. Finding and posing research questions, obtaining an accurate and useful dataset that matched the criteria and manipulating that to answer specific as well as vague questions to name a few. 
However, this project has been a valuable learning experience for me and now, although I'm not perfect, I know where to start and how to go about the entire process. As a coder, this project has helped me think not only from a logical standpoint but a pattern-detecting and hypothesizing perspective. To write code is one thing, but to understand what it is doing and how it is helpful/can contribute to more human understanding is what this project is opening my eyes to. 


#### Appendix 3: Use of Envisioning Cards  
There has beena lack of usage in Envisioning Cards as we have basic background in the topics we discussed, further improvement with these cards will be done later.


